import type { AetherisTheme } from './types'

export const AETHERIS_THEMES: Record<string, AetherisTheme> = {
  tarot: {
    id: 'tarot',
    label: 'Tarot do Destino',
    subtitle: 'Passado · Presente · Futuro',
    accentColor: '#7000ff',
    accentColorLight: '#9b4dff',
    accentColorDark: '#4a00b3',
    glowColor: '#7000ff',
    symbol: '✧',
    cardCount: 3,
    costLabel: '5 Pontos Cósmicos',
    oracleLabel: 'AI.ORACLE',
    oracleStatus: 'CALIBRATING DESTINY',
  },
  daily: {
    id: 'daily',
    label: 'Tarot do Dia',
    subtitle: 'Mensagem Diária do Universo',
    accentColor: '#00f2ff',
    accentColorLight: '#66f7ff',
    accentColorDark: '#00b8c2',
    glowColor: '#00f2ff',
    symbol: '☼',
    cardCount: 1,
    costLabel: 'Grátis',
    oracleLabel: 'AI.SOLAR',
    oracleStatus: 'SCANNING TIMELINE',
  },
  love: {
    id: 'love',
    label: 'Tarot do Amor',
    subtitle: 'Você · Parceiro · Destino',
    accentColor: '#ff2d78',
    accentColorLight: '#ff6ea3',
    accentColorDark: '#c2004f',
    glowColor: '#ff2d78',
    symbol: '♡',
    cardCount: 3,
    costLabel: '15 Pontos Cósmicos',
    oracleLabel: 'AI.EROS',
    oracleStatus: 'SYNCING HEARTS',
  },
  cigano: {
    id: 'cigano',
    label: 'Baralho Cigano',
    subtitle: 'Método das 5 Cartas',
    accentColor: '#00e68a',
    accentColorLight: '#66f0b8',
    accentColorDark: '#00a35e',
    glowColor: '#00e68a',
    symbol: '◈',
    cardCount: 5,
    costLabel: '7 Pontos Cósmicos',
    oracleLabel: 'AI.LENORMAND',
    oracleStatus: 'READING PATTERNS',
  },
  yesno: {
    id: 'yesno',
    label: 'Sim ou Não',
    subtitle: 'Resposta Direta do Oráculo',
    accentColor: '#00f2ff',
    accentColorLight: '#66f7ff',
    accentColorDark: '#00b8c2',
    glowColor: '#00f2ff',
    symbol: '⟁',
    cardCount: 1,
    costLabel: '1 Ponto Cósmico',
    oracleLabel: 'AI.BINARY',
    oracleStatus: 'COMPUTING FATE',
  },
  semanal: {
    id: 'semanal',
    label: 'Tarot Semanal',
    subtitle: 'Previsão dos 7 Dias',
    accentColor: '#ffcc33',
    accentColorLight: '#ffe066',
    accentColorDark: '#cc9900',
    glowColor: '#ffcc33',
    symbol: '⟡',
    cardCount: 7,
    costLabel: '50 Pontos Cósmicos',
    oracleLabel: 'AI.CHRONOS',
    oracleStatus: 'MAPPING WEEK',
  },
}
